development:
  cloud_name: ENV["CL_NAME"]
  api_key: ENV["CL_KEY"]
  api_secret: ENV["CL_SECRET"]
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ENV["CL_NAME"]
  api_key: ENV["CL_KEY"]
  api_secret: ENV["CL_SECRET"]
  enhance_image_tag: true
  static_image_support: true
